__version__ = '0.6.3'
__url__ = 'https://github.com/tolstislon/pytest-bug'
__description__ = 'Pytest plugin Mark test as a bug'
__author__ = 'tolstislon'
__author_email__ = 'tolstislon@gmail.com'
__license__ = 'MIT License'
